export enum StateStatus {
  NOT_STARTED = 0,
  STARTED = 1,
  FINISHED = 2,
}

export const enum PlayerAnimationState {
  "idle" = "idle",
  "walk_left" = "walk_left",
  "idle_left" = "idle_left",
  "walk_right" = "walk_right",
  "idle_right" = "idle_right",
  "walk_up" = "walk_up",
  "idle_up" = "idle_up",
  "throw_boomerang_up" = "throw_boomerang_up",
  "walk_down" = "walk_down",
  "idle_down" = "idle_down",
  "throw_boomerang_down" = "throw_boomerang_down",
  "eat_left" = "eat_left",
  "eat_right" = "eat_right",
  "get_hurt_left" = "get_hurt_left",
  "get_hurt_right" = "get_hurt_right",
  "draw_guns" = "draw_guns",
  "play_with_boomerang" = "play_with_boomerang",
  "play_with_bomb" = "play_with_bomb",
  "thumbs_up" = "thumbs_up",
  "wave" = "wave",
  "teleport_in" = "teleport_in",
  "teleport_out" = "teleport_out",
  "throw_boomerang_left" = "throw_boomerang_left",
  "throw_boomerang_right" = "throw_boomerang_right",
  "lay_bomb_left" = "lay_bomb_left",
  "lay_bomb_right" = "lay_bomb_right",
  "club_attack_one_up" = "club_attack_one_up",
  "club_attack_two_up" = "club_attack_two_up",
  "club_attack_one_down" = "club_attack_one_down",
  "club_attack_two_down" = "club_attack_two_down",
  "club_attack_one_right" = "club_attack_one_right",
  "club_attack_two_right" = "club_attack_two_right",
  "club_attack_one_left" = "club_attack_one_left",
  "club_attack_two_left" = "club_attack_two_left",
  "get_hurt_down" = "get_hurt_down",
  "get_hurt_up" = "get_hurt_up",
  "club_swipe_down_from_left" = "club_swipe_down_from_left",
  "club_swipe_down_from_right" = "club_swipe_down_from_right",
  "club_swipe_right_from_top" = "club_swipe_right_from_top",
  "club_swipe_right_from_bottom" = "club_swipe_right_from_bottom",
  "club_swipe_left_from_top" = "club_swipe_left_from_top",
  "club_swipe_left_from_bottom" = "club_swipe_left_from_bottom",
  "club_swipe_up_from_left" = "club_swipe_up_from_left",
  "club_swipe_up_from_right" = "club_swipe_up_from_right",
}

export const enum PlayerState {
  idle = "idle",
  walk = "walk",
  club_attack = "club_attack",
}
